-- Run this script in the Supabase SQL Editor

-- ================================================================
-- 1. Create the 'posts' table (If you haven't already)
-- ================================================================
CREATE TABLE IF NOT EXISTS public.posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    media_url TEXT NOT NULL,
    media_type TEXT NOT NULL CHECK (media_type IN ('image', 'video')),
    caption TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ================================================================
-- 2. Enable Row Level Security (RLS) for the table
-- ================================================================
ALTER TABLE public.posts ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- 3. Create Policies for the 'posts' TABLE
-- ================================================================

-- Allow anyone to view posts
CREATE POLICY "Public posts are viewable by everyone" ON public.posts
    FOR SELECT USING (true);

-- Allow authenticated users to insert their own posts
CREATE POLICY "Users can insert their own posts" ON public.posts
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Allow users to update their own posts
CREATE POLICY "Users can update their own posts" ON public.posts
    FOR UPDATE USING (auth.uid() = user_id);

-- Allow users to delete their own posts
CREATE POLICY "Users can delete their own posts" ON public.posts
    FOR DELETE USING (auth.uid() = user_id);

-- ================================================================
-- 4. STORAGE POLICIES for 'posts' BUCKET
-- ================================================================
-- Since you created a PUBLIC bucket named 'posts', you still need
-- policies to allow uploads and deletions.

-- 4a. Allow Public Access to View Files (already true for public buckets, but good to be explicit)
CREATE POLICY "Public Access" ON storage.objects
    FOR SELECT USING ( bucket_id = 'posts' );

-- 4b. Allow Authenticated Users to Upload Files
-- This allows any logged-in user to upload to the 'posts' bucket
CREATE POLICY "Authenticated Upload" ON storage.objects
    FOR INSERT 
    WITH CHECK ( bucket_id = 'posts' AND auth.role() = 'authenticated' );

-- 4c. Allow Users to Delete Their Own Files
-- This is important! A user should only be able to delete files they own.
CREATE POLICY "Owner Delete" ON storage.objects
    FOR DELETE
    USING ( bucket_id = 'posts' AND auth.uid() = owner );
