-- ================================================================
-- Run this script in the Supabase SQL Editor
-- ================================================================

-- ================================================================
-- 1. Create the 'posts' table
-- ================================================================
-- NOTE: We store 'storage_path' instead of a full URL
--       because the bucket is PRIVATE and we generate
--       short-lived signed URLs at runtime.
-- ================================================================
CREATE TABLE IF NOT EXISTS public.usersposts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    storage_path TEXT NOT NULL,              -- e.g. 'userId/1708512345_photo.jpg'
    media_type TEXT NOT NULL CHECK (media_type IN ('image', 'video')),
    caption TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- ================================================================
-- 2. Enable Row Level Security (RLS)
-- ================================================================
ALTER TABLE public.usersposts ENABLE ROW LEVEL SECURITY;

-- ================================================================
-- 3. RLS Policies for the 'posts' TABLE
-- ================================================================

-- Anyone authenticated can view all posts
CREATE POLICY "Authenticated users can view posts" ON public.usersposts
    FOR SELECT USING (auth.role() = 'authenticated');

-- Users can insert their own posts
CREATE POLICY "Users can insert their own posts" ON public.usersposts
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users can update their own posts
CREATE POLICY "Users can update their own posts" ON public.usersposts
    FOR UPDATE USING (auth.uid() = user_id);

-- Users can delete their own posts
CREATE POLICY "Users can delete their own posts" ON public.usersposts
    FOR DELETE USING (auth.uid() = user_id);


-- ================================================================
-- 4. STORAGE POLICIES for 'userposts' PRIVATE BUCKET
-- ================================================================
-- IMPORTANT: Create the bucket named 'userposts' as PRIVATE
--            in Supabase Dashboard → Storage → New Bucket
-- ================================================================

-- 4a. Authenticated users can VIEW files (needed for signed URLs to work)
CREATE POLICY "Auth users can view userposts" ON storage.objects
    FOR SELECT USING (
        bucket_id = 'userposts'
        AND auth.role() = 'authenticated'
    );

-- 4b. Authenticated users can UPLOAD files into their own folder
CREATE POLICY "Auth users can upload to userposts" ON storage.objects
    FOR INSERT WITH CHECK (
        bucket_id = 'userposts'
        AND auth.role() = 'authenticated'
        AND (storage.foldername(name))[1] = auth.uid()::text
    );

-- 4c. Users can UPDATE their own files
CREATE POLICY "Users can update own userposts" ON storage.objects
    FOR UPDATE USING (
        bucket_id = 'userposts'
        AND auth.uid()::text = (storage.foldername(name))[1]
    );

-- 4d. Users can DELETE their own files
CREATE POLICY "Users can delete own userposts" ON storage.objects
    FOR DELETE USING (
        bucket_id = 'userposts'
        AND auth.uid()::text = (storage.foldername(name))[1]
    );
